# Generated by Django 3.1.4 on 2020-12-25 06:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15, null=True, unique=True)),
                ('contact_person', models.CharField(max_length=50)),
                ('primary_contact_number', models.BigIntegerField(unique=True)),
                ('secondary_contact_number', models.BigIntegerField(null=True, unique=True)),
                ('email_address', models.EmailField(max_length=254, null=True, unique=True)),
                ('street_address', models.TextField(max_length=250)),
                ('pin_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True)),
                ('employee_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.designation')),
            ],
            options={
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='items_produced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name here', max_length=50)),
                ('product_description', models.CharField(help_text='Write something about the product here', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='user_firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15, null=True, unique=True)),
                ('contact_person', models.CharField(max_length=50)),
                ('primary_contact_number', models.BigIntegerField(unique=True)),
                ('secondary_contact_number', models.BigIntegerField(null=True, unique=True)),
                ('email_address', models.EmailField(max_length=254, null=True, unique=True)),
                ('street_address', models.TextField(max_length=250)),
                ('pin_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('remarks', models.TextField(max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15, null=True, unique=True)),
                ('contact_person', models.CharField(max_length=50)),
                ('primary_contact_number', models.BigIntegerField(unique=True)),
                ('secondary_contact_number', models.BigIntegerField(null=True, unique=True)),
                ('email_address', models.EmailField(max_length=254, null=True, unique=True)),
                ('street_address', models.TextField(max_length=250)),
                ('pin_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
                ('firm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
            ],
        ),
        migrations.CreateModel(
            name='sales_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('freight', models.PositiveIntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('total_amount', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
            ],
        ),
        migrations.CreateModel(
            name='sales_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('gst_rate', models.PositiveSmallIntegerField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sales_order')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('freight', models.PositiveIntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('total_amount', models.PositiveIntegerField()),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('gst_rate', models.PositiveSmallIntegerField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='production_volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('data_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('firm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('gst_rate', models.PositiveSmallIntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('firm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product_category'),
        ),
        migrations.CreateModel(
            name='maintenance_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('days_engaged', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('firm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.machines')),
            ],
        ),
        migrations.AddField(
            model_name='machines',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
        migrations.AddField(
            model_name='machines',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.employee'),
        ),
        migrations.CreateModel(
            name='KPIList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('firm', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
        migrations.AddField(
            model_name='customer',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
    ]
