# Generated by Django 3.1.4 on 2020-12-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201226_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='gst_rate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='remarks',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='gst_rate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='firm',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.user_firm'),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='remarks',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
