# Generated by Django 3.1.4 on 2020-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201227_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_firm',
            name='remarks',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
