# Generated by Django 3.1.4 on 2020-12-31 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201231_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
